// solid/app/SearchParams.jsx
import { For, createSignal, createResource } from "solid-js";
import Pet from "./Pet";

const SearchParams = () => {
  const animals = ["bird", "cat", "dog"];
  const [location, setLocation] = createSignal("");
  const [animal, setAnimal] = createSignal("");
  const [breed, setBreed] = createSignal("");
  const [breeds, setBreeds] = createSignal([]);

  const [pets, { _, refetch }] = createResource(async () => {
    const res = await fetch(
      `http://pets-v2.dev-apis.com/pets?animal=${animal()}&location=${location()}&breed=${breed()}`
    );
    const json = await res.json();
    return json.pets;
  });

  return (
    <>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          refetch();
        }}
      >
        <label htmlFor="location">
          Location
          <input
            id="location"
            placeholder="Location"
            value={location()}
            onChange={(e) => {
              setLocation(e.target.value);
            }}
          />
        </label>
        <label htmlFor="animal">
          Animal
          <select
            htmlFor="animal"
            value={animal}
            onChange={(e) => {
              setAnimal(e.target.value);
              setBreeds([]);
              setBreed("");
            }}
          >
            <option />
            {animals.map((animal) => (
              <option key={animal} value={animal}>
                {animal}
              </option>
            ))}
          </select>
        </label>
        <label htmlFor="breed">
          Breed
          <select
            htmlFor="breed"
            value={breed}
            onChange={(e) => setBreed(e.target.value)}
            disabled={breeds().length === 0}
          >
            <option />
            <For each={breeds()}>
              {(breed) => (
                <option key={breed} value={breed}>
                  {breed}
                </option>
              )}
            </For>
          </select>
        </label>
        <button>Submit</button>
      </form>
      <For each={pets()}>
        {(pet) => (
          <Pet
            name={pet.name}
            animal={pet.animal}
            breed={pet.breed}
            key={pet.id}
          />
        )}
      </For>
    </>
  );
};

export default SearchParams;

// react/app/SearchParams.jsx
import { useEffect, useState } from "react";
import Pet from "./Pet";

const SearchParams = () => {
  const animals = ["bird", "cat", "dog"];
  const [location, setLocation] = useState("");
  const [animal, setAnimal] = useState("");
  const [breed, setBreed] = useState("");
  const [breeds, setBreeds] = useState([]);

  const [pets, setPets] = useState([]);

  useEffect(() => {
    fetchPets();
  }, []);

  async function fetchPets() {
    const res = await fetch(
      `http://pets-v2.dev-apis.com/pets?animal=${animal}&location=${location}&breed=${breed}`,
    );
    const json = await res.json();
    setPets(json.pets);
  }

  return (
    <div className="search-params">
      <form
        onSubmit={(e) => {
          e.preventDefault();
          fetchPets();
        }}
      >
        <label htmlFor="location">
          Location
          <input
            id="location"
            value={location}
            placeholder="Location"
            onChange={(e) => setLocation(e.target.value)}
          />
        </label>
        <label htmlFor="animal">
          Animal
          <select
            htmlFor="animal"
            value={animal}
            onChange={(e) => {
              setAnimal(e.target.value);
              setBreeds([]);
              setBreed("");
            }}
          >
            <option />
            {animals.map((animal) => (
              <option key={animal} value={animal}>
                {animal}
              </option>
            ))}
          </select>
        </label>
        <label htmlFor="animal">
          Breed
          <select
            htmlFor="breed"
            value={breed}
            onChange={(e) => setBreed(e.target.value)}
            disabled={breeds.length === 0}
          >
            <option />
            {breeds.map((breed) => (
              <option key={breed} value={breed}>
                {breed}
              </option>
            ))}
          </select>
        </label>
        <button>Submit</button>
      </form>

      {pets.map((pet) => (
        <Pet
          name={pet.name}
          animal={pet.animal}
          breed={pet.breed}
          key={pet.id}
        />
      ))}
    </div>
  );
};

export default SearchParams;
